# name: JS - Unit Tests

# on: push

# jobs:

#   run-tests:
#     name: Unit Tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 20.11.0

#       - name: Install dependencies with caching
#         uses: bahmutov/npm-install@v1

#       - name: Check types
#         run: |
#           yarn run typecheck

#       - name: Run unit tests
#         run: |
#           yarn run test

# name: CI/CD

# on: push

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 20.11.0

#       - name: Run tests
#         run: npm test

#   deploy:
#     needs: build-and-test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Install Netlify CLI
#         run: npm install netlify-cli -g

#       - name: Deploy to Netlify
#         run: netlify deploy --prod
#         env:
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


# name: CI/CD

# on: push

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 20.11.0

#       - name: Install dependencies
#         run: npm ci

#       - name: Install Jest
#         run: npm install --save-dev jest

#       - name: Run tests
#         run: npx jest

#   deploy:
#     needs: build-and-test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Install Netlify CLI
#         run: npm install netlify-cli -g

#       - name: Deploy to Netlify
#         run: netlify deploy --prod
#         env:
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


# name: CI/CD

# on: push

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 20.11.0

#       - name: Generate package-lock.json (if not exists)
#         run: |
#           if [ ! -f package-lock.json ]; then
#             npm install --package-lock-only
#           fi

#       - name: Install dependencies
#         run: npm ci

#       - name: Run tests
#         run: npm test

#   deploy:
#     needs: build-and-test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Install Netlify CLI
#         run: npm install netlify-cli -g

#       - name: Deploy to Netlify
#         run: netlify deploy --prod
#         env:
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


# name: CI/CD

# on: push

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 20.11.0

#       # - name: Generate package-lock.json (if not exists)
#       #   run: |
#       #     if [ ! -f package-lock.json ]; then
#       #       npm install --package-lock-only
#       #     fi

#       - name: Install dependencies
#         run: npm ci

#       - name: Build project
#         run: npm run build

#       - name: Run tests
#         run: npm test

#   deploy:
#     needs: build-and-test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Install Netlify CLI
#         run: npm install netlify-cli -g

#       - name: Deploy to Netlify
#         run: netlify deploy --prod
#         env:
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


name: CI/CD

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Deploy to Netlify
        run: netlify deploy --prod
        # working-directory: ./dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
